//Login
export const LOGIN_SUCCESSFULLY = "LOGIN_SUCCESSFULLY";
export const LOGIN_FAILED = "LOGIN_FAILED";

//Register
export const REGISTER_SUCCESSFULLY = "REGISTER_SUCCESSFULLY";
export const REGISTER_FAILED = "REGISTER_FAILED";

//Logout
export const LOGOUT_SUCCESSFULLY = "LOGOUT_SUCCESSFULLY";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

//Like, dislike
export const REACT_LIKE = "REACT_LIKE";
export const REACT_DISLIKE = "REACT_DISLIKE";
export const GET_REACT_SUCCESSFULLY = "GET_REACT_SUCCESSFULLY";

export const GET_RECOMMEND_LIST_SUCCESSFULLY =
  "GET_RECOMMEND_LIST_SUCCESSFULLY";
