//Login
export const LOGIN_SUCCESSFULLY = 'LOGIN_SUCCESSFULLY';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//Logout
export const LOGOUT_SUCCESSFULLY = 'LOGOUT_SUCCESSFULLY';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';