//Login
export const LOGIN_SUCCESSFULLY = 'LOGIN_SUCCESSFULLY';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//Register
export const REGISTER_SUCCESSFULLY = 'REGISTER_SUCCESSFULLY';
export const REGISTER_FAILED = 'REGISTER_FAILED';

//Logout
export const LOGOUT_SUCCESSFULLY = 'LOGOUT_SUCCESSFULLY';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';